spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user?createDatabaseIfNotExist=true
    username: root
    password: 1258
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
      
  application:
    name: user-service
server:
  port: 8082
  
  
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/